#Requires -Version 5.1
param([string]$ConfigPath)

$localConfigPath = if ($ConfigPath) { $ConfigPath } else { Join-Path (Split-Path -Parent $PSScriptRoot) "config\box_mount.local.cmd" }
New-Item -ItemType Directory -Path (Split-Path -Parent $localConfigPath) -Force | Out-Null
$userProfilePath = [System.IO.Path]::GetFullPath($env:USERPROFILE).TrimEnd('\')
$defaultTarget = $userProfilePath
if (Test-Path -LiteralPath $localConfigPath -PathType Leaf) {
    Get-Content -LiteralPath $localConfigPath | ForEach-Object {
        if ($_ -match '^\s*set\s+"TARGET_DIR=(.*)"\s*$') { $defaultTarget = $Matches[1] }
    }
}

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

function Save-BoxMountConfig {
    param([bool]$Enabled, [string]$TargetDir)
    $lines = @('@echo off', 'rem Generated by configure_box_mount.ps1.', "set `"BOX_ENABLED=$(if ($Enabled) { '1' } else { '0' })`"")
    if ($Enabled) {
        $lines += "set `"TARGET_DIR=$TargetDir`""
    }
    Set-Content -LiteralPath $localConfigPath -Value $lines -Encoding ASCII
}

$form = New-Object System.Windows.Forms.Form
$form.Text = '共有フォルダ設定'
$form.StartPosition = 'CenterScreen'
$form.FormBorderStyle = 'FixedDialog'
$form.MaximizeBox = $false
$form.MinimizeBox = $false
$form.ClientSize = New-Object System.Drawing.Size(460,230)
$form.Font = New-Object System.Drawing.Font('Meiryo UI',9)

$intro = New-Object System.Windows.Forms.Label
$intro.Text = 'Box の共有フォルダを選択してください。選んだ実体パスを設定として保存します。'
$intro.Location = New-Object System.Drawing.Point(14,14)
$intro.Size = New-Object System.Drawing.Size(432,60)
$form.Controls.Add($intro)

$startLabel = New-Object System.Windows.Forms.Label
$startLabel.Text = "選択の開始位置（このユーザーの実体パス）: $userProfilePath"
$startLabel.Location = New-Object System.Drawing.Point(14,70)
$startLabel.Size = New-Object System.Drawing.Size(432,32)
$form.Controls.Add($startLabel)

$pathLabel = New-Object System.Windows.Forms.Label
$pathLabel.Text = '共有フォルダのローカルパス:'
$pathLabel.Location = New-Object System.Drawing.Point(14,112)
$pathLabel.AutoSize = $true
$form.Controls.Add($pathLabel)

$pathBox = New-Object System.Windows.Forms.TextBox
$pathBox.Text = $defaultTarget
$pathBox.Location = New-Object System.Drawing.Point(14,132)
$pathBox.Size = New-Object System.Drawing.Size(340,22)
$form.Controls.Add($pathBox)

$browse = New-Object System.Windows.Forms.Button
$browse.Text = '参照...'
$browse.Location = New-Object System.Drawing.Point(362,130)
$browse.Size = New-Object System.Drawing.Size(84,26)
$browse.Add_Click({
    $dialog = New-Object System.Windows.Forms.FolderBrowserDialog
    $dialog.Description = 'このユーザーの Box 共有フォルダ（マウント元）を選択してください'
    $dialog.ShowNewFolderButton = $false
    $dialog.SelectedPath = if (Test-Path -LiteralPath $pathBox.Text -PathType Container) { $pathBox.Text } else { $userProfilePath }
    if ($dialog.ShowDialog($form) -eq [System.Windows.Forms.DialogResult]::OK) { $pathBox.Text = $dialog.SelectedPath }
})
$form.Controls.Add($browse)


$skip = New-Object System.Windows.Forms.Button
$skip.Text = '使用しない'
$skip.Location = New-Object System.Drawing.Point(14,188)
$skip.Size = New-Object System.Drawing.Size(110,32)
$skip.Add_Click({ Save-BoxMountConfig -Enabled $false -TargetDir ''; $form.Close() })
$form.Controls.Add($skip)

$ok = New-Object System.Windows.Forms.Button
$ok.Text = 'この設定で開始'
$ok.Location = New-Object System.Drawing.Point(336,188)
$ok.Size = New-Object System.Drawing.Size(110,32)
$ok.Add_Click({
    $target = $pathBox.Text.Trim()
    if ([string]::IsNullOrWhiteSpace($target)) {
        [System.Windows.Forms.MessageBox]::Show('共有フォルダのパスを指定してください。','入力エラー') | Out-Null
        return
    }
    if (-not (Test-Path -LiteralPath $target -PathType Container)) {
        [System.Windows.Forms.MessageBox]::Show('存在する共有フォルダのパスを指定してください。','入力エラー') | Out-Null
        return
    }
    $target = [System.IO.Path]::GetFullPath((Resolve-Path -LiteralPath $target -ErrorAction Stop).Path).TrimEnd('\')
    if (-not ($target -eq $userProfilePath -or $target.StartsWith(($userProfilePath + '\'), [System.StringComparison]::OrdinalIgnoreCase))) {
        [System.Windows.Forms.MessageBox]::Show("このユーザーの実体パス配下を選択してください。`n$userProfilePath",'入力エラー') | Out-Null
        return
    }
    Save-BoxMountConfig -Enabled $true -TargetDir $target
    $form.Close()
})
$form.Controls.Add($ok)
[void]$form.ShowDialog()